pass_handler/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('storer.urls')),
    path('users/', include("users.urls")),
]

storer/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("getPassword", views.getPassword, name="getPassword")
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('', views.index),
    path('login/', views.login_view, name='login'),
]

storer/models.py
from django.db import models

class Password(models.Model):
    website = models.CharField(unique=True, max_length=200)
    password = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.website}: {self.password}"

users/models.py
from django.db import models

user = models.ForeignKey('auth.User', on_delete=models.CASCADE)

storer/views.py
from django.shortcuts import render
from .models import Password
from django.urls import reverse
from django.http import Http404, JsonResponse, HttpResponseRedirect, HttpResponse
import json
from django.contrib.auth import authenticate
#from django.views.decorators.csrf import csrf_exempt

#@csrf_exempt
def index(request):
    if not request.user.is_authenticated:
        print("logged out")
        already_present.clear()
        return render(request, "users/login.html")

    print("logged in")
    if request.method == "GET":
        return render(request, "storer/index.html")


already_present = list()    
def getPassword(request):

    if not request.user.is_authenticated:
        raise Http404("Not Found")

    if request.method == "GET":
        context = []
        for ele in already_present:
            object = Password.objects.filter(website=ele).values('website', 'password')
            context.append(object[0])
        return JsonResponse(context, safe=False, status = 200)
    
    data = json.loads(request.body)

    print(data)
    context = []
    
    try:
        objects = Password.objects.filter(website__icontains=data).values('website', 'password')
        for ele in objects:
            if ele["website"] not in already_present:
                context.append(ele)
                already_present.append(ele["website"])
    except Exception as e: 
        print(e)

    return JsonResponse(context, safe=False, status=200)

users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpRequest, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout


def index(request):
    logout(request)
    print("logged out")
    return render(request, "users/login.html")

def login_view(request):
    if not request.method == "POST":
        return index(request)
        
    username = request.POST["username"]
    password = request.POST["password"]

    user = authenticate(request, username=username, password=password)

    print(user)
    if user is None:
        return index(request)
    else:
        login(request, user)
        return HttpResponseRedirect(reverse("index")) 
        
    

storer/templates/storer/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    
    <nav class="navbar">
        <ul class="navbar-nav">
            <li class="logo">
                <a href="#" class="nav-link">
                    <span class="hamburger"><i class="fas fa-hamburger"></i></span>
                    <span class="link-text">MENU</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <span class="icon"><i class="fa fa-address-book"></i></span>
                    <span class="link-text">Cats</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link">
                    <span class="icon"><i class="fas fa-dog"></i></span>
                    <span class="link-text">Aliens</span>
                </a>
            </li>

            <li class="nav-item">
                <a href="#" class="nav-link">
                    <span class="icon"><i class="fa fa-address-book"></i></span>
                    <span class="link-text">dogsy</span>
                </a>
            </li>
        </ul>
    </nav>

    {% block body %} {% endblock %}
    <link rel="stylesheet" href="{% static 'storer/navbar.css' %}">
</body>
</html>

storer/templates/storer/index.html
{% extends "storer/base.html" %}
{% load static %}

{% block title %} 
    index
{% endblock %}

{% block body %} 
    
    <main>    
        <h1 class="title">Password Manager</h1>
        <form id="search-form" class="search-form">
            {% csrf_token %}
            <div class="form-group">
                <label class="above-input">Keyword</label>
                <input type="text" class="form-input" id="search-entity" autocomplete="off">
                <small class="below-input">We'll never share your password with anyone else.</small>
            </div>
            <button type="submit" class="btn-submit" id="btn-submit">Submit</button>
        </form>
            
        <div class="password-container">
            <ul id="password-list">
            </ul>
        </div>
    </main>


    <script src="{% static 'storer/index.js' %}"></script>
    <script src="{% static 'storer/hel.js' %}"></script>
    <link rel="stylesheet" href="{% static 'storer/index.css' %}">
    <!--<script src="https://kit.fontawesome.com/a076d05399.js"></script>-->
    <link rel="stylesheet" href="{% static 'storer/fontawesome/css/all.css' %}">
{% endblock %}

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Login</h1>
    <form action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="username" placeholder="username">
        <input type="password" name="password" placeholder="password">
        <input type="submit" value="login">
    </form>
</body>
</html>